# otel-demo/templates/deployment.yaml
{{- range $service, $config := .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $service }}
  template:
    metadata:
      labels:
        app: {{ $service }}
    spec:
      containers:
        - name: {{ $service }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          ports:
            - containerPort: {{ $config.port }}
---
{{- end }}
