# otel-demo/templates/service.yaml
{{- range $service, $config := .Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service }}
spec:
  selector:
    app: {{ $service }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
---
{{- end }}
