pipeline {
    agent any

    environment {
        Frontend_URL = 'http://jayavardhanreddy616.xyz'
        Report_Name = 'zap-report.html'
    }

    stages {
        stage('ZAP Scan') {
            steps {
                sh '''
                    echo "Running ZAP Scan on $Frontend_URL"

                    docker run --rm -v $(pwd):/zap/wrk/:rw securecodebox/zap:latest \
                        zap-baseline.py -t $Frontend_URL -g gen.conf -r $Report_Name

                    echo "ZAP Scan completed. Report saved as $Report_Name"
                '''
            }
        }
    }
}
