apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-proxy

spec:
  ingressClassName: gce
  rules:
    - host: example.com

      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: opentelemetry-demo-frontendproxy
                port:
                  number: 8080
