############################
# CARTSERVICE Deployment
############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: {{ .Values.cartservice.replicaCount }}
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: {{ .Values.cartservice.image }}
          ports:
            - containerPort: {{ .Values.cartservice.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.cartservice.port }}

############################
# FRONTEND Deployment
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}

############################
# FRONTENDPROXY Deployment
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendproxy
spec:
  replicas: {{ .Values.frontendproxy.replicaCount }}
  selector:
    matchLabels:
      app: frontendproxy
  template:
    metadata:
      labels:
        app: frontendproxy
    spec:
      containers:
        - name: frontendproxy
          image: {{ .Values.frontendproxy.image }}
          ports:
            - containerPort: {{ .Values.frontendproxy.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontendproxy
spec:
  selector:
    app: frontendproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontendproxy.port }}
