cartservice:
  image: ghcr.io/open-telemetry/demo:1.12.0-cartservice
  replicaCount: 1
  port: 7070

frontend:
  image: ghcr.io/open-telemetry/demo:1.12.0-frontend
  replicaCount: 1
  port: 8080

frontendproxy:
  image: ghcr.io/open-telemetry/demo:1.12.0-frontendproxy
  replicaCount: 1
  port: 8083
