cartservice:
  image:
    repository: hashicorp/http-echo
    tag: latest
  replicaCount: 1
  port: 7070
  service:
    type: ClusterIP
  args:
    - "-text=Hello from Cart Service"
    - "-listen=:7070"

frontend:
  image:
    repository: hashicorp/http-echo
    tag: latest
  replicaCount: 1
  port: 8080
  service:
    type: ClusterIP
  args:
    - "-text=Hello from Frontend"

frontendproxy:
  enabled: true
  image:
    repository: hashicorp/http-echo
    tag: latest
  replicaCount: 1
  port: 8081
  service:
    type: ClusterIP
  args:
    - "-text=Hello from Frontend Proxy"
