frontend:
  image:
    repository: ghcr.io/open-telemetry/demo
    tag: 1.12.0-frontend
  replicaCount: 2
  port: 8080
  frontendproxy:    # <-- Incorrect: nested under frontend
    enabled: true
    image:
      repository: ghcr.io/open-telemetry/demo
      tag: 1.12.0-frontend-proxy
    replicaCount: 2
    port: 8081
