cartservice:
  image:
    repository: ghcr.io/open-telemetry/demo
    tag: 1.12.0-cartservice
  replicaCount: 2
  port: 7070
  type: clusterip

frontend:
  image:
    repository: ghcr.io/open-telemetry/demo
    tag: 1.12.0-frontend
  replicaCount: 2
  port: 8080
  type: clusterip

frontendproxy:
  enabled: true
  image:
    repository: ghcr.io/open-telemetry/demo
    tag: 1.12.0-frontend-proxy
  replicaCount: 1
  port: 8081
  type: clusterip
