# CI for Product Catalog Service

name: CI for Product Catalog Service

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Setup Go 1.22
          uses: actions/setup-go@v4
          with:
            go-version: 1.22

        - name: Build
          run: |
            cd src/product-catalog
            go mod download
            go build -o product-catalog-service main.go

        - name: unit tests
          run: |
            cd src/product-catalog
            go test ./...

    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Run golangci-lint
          run:
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest && \
            golangci-lint run src/product-catalog-service/...

    docker:
        runs-on: ubuntu-latest

        needs: build

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: install docker
          uses: docker/setup-buildx-action@v2

        - name: login to docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: docker push
          uses: docker/build-push-action@v6
          with:
            context: src/product-catalog-service
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
    
    jobs:
      runs-on: ubuntu-latest
      
      needs: docker

      steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: update image in kubernetes deployment manifest
        run: | 
          sed -i 's|image: .*|image: '${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}'|g' kubernetes/productcatalog/deploy.yaml
      
      - name: commit changes
        run: |
          git config --global user.email "robertteah@gmail.com"
          git config --global user.name "Robert Teah"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI]: Update product catalog image tag"
          git push origin HEAD:main -f
