# This workflow is triggered on pull requests to the main branch.
name: product-catalog-ci
on:
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up go 1.22
              uses: actions/setup-go@v4
              with:
                go-version: 1.22
            - name: build
              run: |
                cd src/product-catalog
                go mod download
                go build -o product-catalog-service main.go

            - name: Run unit test
              run: |
                cd src/product-catalog
                go test ./...

    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: setup Go 1.22
              uses: actions/setup-go@v4
              with:
                go-version: 1.22
            - name: Run golangci-lint
              run: 
                go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
                golangci-lint run src/product-catalog/...
    
    docker:
        runs-on: ubuntu-latest

        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                context: src/product-catalog
                file: src/product-catalog/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}

            
    update_k8s:
        runs-on: ubuntu-latest

        needs: docker

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: update k8s mainfest
              run: |
                    sed -i 's/image: .*/image: ${{ secrets.DOCKER_USERNAME}}/product-catalog:${{github.run_id}}/' kubernetes/prodcutcatalog/deploy.yaml

            - name: commit and push changes
              run: |
                 git config --global user.name "raghudev"
                 git config --global user.email "raghudev.pulligilla@gmail.com"
                 git add kubernetes/prodcutcatalog/deploy.yaml
                 git commit -m "[CI]: updated image"
                 git push 
                 
                    