name: product-catalog-ci
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: go build -o product-catalog-service src/product-catalog-service/main.go

      - name: Run unit tests
        run: go test src/product-catalog-service/...
  
  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Linting
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          args: --timeout 5m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: [build, code-quality]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: src/product-catalog-service
          dockerfile: src/product-catalog-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-catalog-service:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/product-catalog-service:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/product-catalog-service:cache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update tag in Kubernetes manifest
        run: |
          sed -i 's/image: .*/image: "${{ secrets.DOCKERHUB_USERNAME }}/product-catalog-service:${{ github.sha }}"/' kubernetes/productcatalog/deploy.yaml
      
      - name: Commit and Push changes
        run: |
          git config --local user.name "kiranbakale"
          git config --local user.email "kiranbakale9@gmail.com"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI]: Update product catalog image tag"
          git push
