# CI for product catalog

name: product-catalog-ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      
      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog main.go

      - name: unit tests
        run: |
          cd src/product-catalog
          go test ./...


  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run golang-lint
        run: |
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
              golangci-lint run src/product-catalog/...

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install docker
        uses: docker/setup-buildx-action@v2

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: src/product-catalog/
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id}}
      
  updatek8s:
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
        token: ${{ secrets.TOKEN }}
      
      - name: Update K8s tags
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}/' kubernetes/productcatalog/deploy.yaml
      
      - name: Commit and Push changes
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ secrets.USERNAME }}"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI] Update K8s deployment image tag"
          git push
