# This workflow runs the CI pipeline for the Product Catalog service.
name: product-catalog-ci
on:
    pull_request:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: setup Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
        - name: build
          run: |
            cd src/product-catalog
            go mod download
            go build -o product-catalog-service src/product-catalog/main.go
        - name: unit-tests
          run: |
            cd src/product-catalog
            go test ./...
    code-quality:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.55.2
            working-directory: src/product-catalog
    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: install docker
          uses: docker/setup-buildx-action@v2
        - name: docker login
          uses: docker/login-action@v2
          with:
            registry: docker.io
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: build and push docker image
          uses: docker/build-push-action@v6
          with:
            context: src/product-catalog
            file: src/product-catalog/Dockerfile
            push: true
            tags: ${{ vars.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
    kubernetes:
        runs-on: ubuntu-latest
        needs: docker
        steps:
        - name: checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}
        - name: update tag in kubernetes deployment manifest
          run: |
            sed -i 's|image: .*|image: '${{ vars.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}'|g' kubernetes/product-catalog/deploy.yaml
        - name: commit and push changes
          run: |
            git config --global user.email "yugandharkanaparthi9@gmail.com"
            git config --global user.name "Yugandharkanaparthi"
            git add kubernetes/product-catalog/deploy.yaml
            git commit -m "Update image tag to ${{ vars.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}"
            git push origin HEAD:main -f

        
        

